// We do not import the mdx files here inorder to make use of dynamic imports inside $postId file
export interface BlogList {
  slug: string;
  title: string;
  publishDate: string;
  description: string;
  readingTime: string;
  imageUrl: string;
}

export const blogList: Array<BlogList> = [
  {
    slug: "Wding", 
    title: "Wedding",
    publishDate: "",
    description:
      "Every blog starts with a single post. This is yours. Make it great.",
    readingTime: "1 min",
    imageUrl: "public/assets/images/wedding1.jpg"
  },
  {
    slug: "Pre Wedding",
    title: "Pre wedding",
    publishDate: "",
    description:
      "A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Use it as a starting point for applying your own styles.",
    readingTime: "5 min",
    imageUrl: "./testing-image.jpg"
  },
  {
    slug: "Baby shower",
    title: "Baby shower",
    publishDate: "",
    description:
      " A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.",
    readingTime: "10 min",
    imageUrl: "./testing-image.jpg"
  },
  {
    slug: "Birthday party",
    title: "Birthday party",
    publishDate: "",
    description:
      " A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.",
    readingTime: "10 min",
    imageUrl: "./testing-image.jpg"
  },
  {
    slug: "Product shoot",
    title: "Product shoot",
    publishDate: "",
    description:
      " A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.",
    readingTime: "10 min",
    imageUrl: "./testing-image.jpg"
  },
  {
    slug: "Fashion shoot",
    title: "Fashion shoot",
    publishDate: "",
    description:
      " A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.",
    readingTime: "10 min",
    imageUrl: "./testing-image.jpg"
  },
];
